"use client";
import {useEffect,useRef,useState} from "react";
import {createChart,IChartApi,ISeriesApi} from "lightweight-charts";
import {calculateIndicator,Candle,IndicatorConfig} from "./indicatorMath";
import {TimeframeSelector} from "./TimeframeSelector";
import {IndicatorMenu} from "./IndicatorMenu";
interface Props{chartId:string;symbol:string;timeframe:string;height?:number;onSymbolClick?:()=>void;onTimeframeChange?:(tf:string)=>void}
interface IndicatorItem{id:string;name:string}
const intervals:Record<string,string>={"1m":"1m","3m":"3m","5m":"5m","15m":"15m","30m":"30m","1H":"1h","4H":"4h","1D":"1d","1W":"1w","1M":"1M"};
const seconds:Record<string,number>={"1m":60,"3m":180,"5m":300,"15m":900,"30m":1800,"1H":3600,"4H":14400,"1D":86400,"1W":604800,"1M":2592000};
const OSCILLATORS=["RSI","MACD","Stochastic","ATR","ADX","CCI","Williams %R"];
const colors=()=>{if(typeof window==="undefined")return{up:"#fff",down:"#666"};try{const p=JSON.parse(localStorage.getItem("jk-candle-colors")||"null");if(p?.up&&p?.down)return{up:p.up,down:p.down}}catch{}return{up:"#fff",down:"#666"}};
const readIndicators=():IndicatorItem[]=>{try{const x=JSON.parse(localStorage.getItem("jk-indicators")||"[]");return Array.isArray(x)?x.map((v:any,i:number)=>typeof v==="string"?{id:`${v}-${i+1}`,name:v}:v&&v.id&&v.name?v:null).filter(Boolean):[]}catch{return[]}};
const readConfig=():Record<string,IndicatorConfig>=>{try{return JSON.parse(localStorage.getItem("jk-indicator-settings")||"{}")||{}}catch{return{}}};
const lineWidth=(value:unknown):1|2|3|4=>{const n=Math.max(1,Math.min(4,Math.round(Number(value)||1)));return n===1?1:n===2?2:n===3?3:4};
const formatCountdown=(sec:number)=>sec>=3600?`${Math.floor(sec/3600)}:${String(Math.floor(sec%3600/60)).padStart(2,"0")}:${String(sec%60).padStart(2,"0")}`:`${Math.floor(sec/60)}:${String(sec%60).padStart(2,"0")}`;
export function ChartPane({chartId,symbol,timeframe,height=400,onSymbolClick,onTimeframeChange}:Props){
 const el=useRef<HTMLDivElement>(null),panesEl=useRef<HTMLDivElement>(null),chart=useRef<IChartApi|null>(null),series=useRef<ISeriesApi<"Candlestick">|null>(null);const indicatorSeries=useRef<any[]>([]),paneCharts=useRef<IChartApi[]>([]);const[indicators,setIndicators]=useState<IndicatorItem[]>([]),[indicatorVersion,setIndicatorVersion]=useState(0),[countdown,setCountdown]=useState(0),[latestPrice,setLatestPrice]=useState<number|null>(null),[countdownTop,setCountdownTop]=useState<number|null>(null);
 useEffect(()=>{setIndicators(readIndicators());const fn=()=>{setIndicators(readIndicators());setIndicatorVersion(v=>v+1)};window.addEventListener("jk-indicators-changed",fn);return()=>window.removeEventListener("jk-indicators-changed",fn)},[]);
 useEffect(()=>{const tick=()=>{const s=seconds[timeframe]||900;const now=Math.floor(Date.now()/1000);const rem=s-(now%s);setCountdown(rem===s?0:rem);if(series.current&&latestPrice!==null){const y=series.current.priceToCoordinate(latestPrice);if(y!==null)setCountdownTop(Math.max(4,Math.min(height-24,y+16)))}};tick();const id=window.setInterval(tick,250);return()=>window.clearInterval(id)},[timeframe,latestPrice,height]);
 useEffect(()=>{if(!el.current)return;const cc=colors(),light=document.documentElement.classList.contains("light");const c=createChart(el.current,{width:Math.max(1,el.current.clientWidth),height,layout:{background:{color:light?"#fff":"#000"},textColor:light?"#111":"#fff"},grid:{vertLines:{color:light?"#e5e5e5":"#1a1a1a"},horzLines:{color:light?"#e5e5e5":"#1a1a1a"}},crosshair:{mode:0},rightPriceScale:{borderColor:light?"#d0d0d0":"#222",minimumWidth:64,scaleMargins:{top:0.08,bottom:0.08}},handleScroll:{mouseWheel:true,pressedMouseMove:true,horzTouchDrag:true},handleScale:{mouseWheel:true,pinch:true,axisPressedMouseMove:true},timeScale:{borderColor:light?"#d0d0d0":"#222",timeVisible:true,rightOffset:3,minBarSpacing:1,fixLeftEdge:false,fixRightEdge:false,lockVisibleTimeRangeOnResize:false,shiftVisibleRangeOnNewBar:true}});const s=c.addCandlestickSeries({upColor:cc.up,downColor:cc.down,borderUpColor:cc.up,borderDownColor:cc.down,wickUpColor:cc.up,wickDownColor:cc.down});chart.current=c;series.current=s;const theme=()=>{const l=document.documentElement.classList.contains("light");c.applyOptions({layout:{background:{color:l?"#fff":"#000"},textColor:l?"#111":"#fff"},grid:{vertLines:{color:l?"#e5e5e5":"#1a1a1a"},horzLines:{color:l?"#e5e5e5":"#1a1a1a"}}})};const col=()=>{const x=colors();s.applyOptions({upColor:x.up,downColor:x.down,borderUpColor:x.up,borderDownColor:x.down,wickUpColor:x.up,wickDownColor:x.down})};const mo=new MutationObserver(theme);mo.observe(document.documentElement,{attributes:true,attributeFilter:["class"]});const ro=new ResizeObserver(()=>{c.applyOptions({width:Math.max(1,el.current?.clientWidth||1),height});if(series.current&&latestPrice!==null){const y=series.current.priceToCoordinate(latestPrice);if(y!==null)setCountdownTop(Math.max(4,Math.min(height-24,y+16)))}});ro.observe(el.current);window.addEventListener("jk-candle-colors-changed",col);return()=>{mo.disconnect();ro.disconnect();window.removeEventListener("jk-candle-colors-changed",col);c.remove();chart.current=null;series.current=null}},[height]);
 useEffect(()=>{let stop=false;let firstLoad=true;const load=async()=>{if(!series.current||!chart.current)return;try{const r=await fetch(`https://api.binance.com/api/v3/klines?symbol=${symbol}&interval=${intervals[timeframe]||"15m"}&limit=1000`,{cache:"no-store"});const raw=await r.json();if(stop||!Array.isArray(raw)||!raw.length)return;const d:Candle[]=raw.map((k:any)=>({time:Math.floor(k[0]/1000) as any,open:+k[1],high:+k[2],low:+k[3],close:+k[4],volume:+k[5]}));const last=d[d.length-1];setLatestPrice(last.close);
 const ts=chart.current.timeScale();const before=ts.getVisibleRange();const wasUserPositioned=before!==null;series.current.setData(d.map(x=>({time:x.time,open:x.open,high:x.high,low:x.low,close:x.close})));
 indicatorSeries.current.forEach(x=>{try{chart.current?.removeSeries(x)}catch{}});indicatorSeries.current=[];paneCharts.current.forEach(x=>{try{x.remove()}catch{}});paneCharts.current=[];const cfgs=readConfig();const oscillators:IndicatorItem[]=[];
 for(const item of indicators){const cfg:any=cfgs[item.id]||cfgs[item.name]||{};const result:any=calculateIndicator(item.name,d,cfg);if(!result)continue;if(result.kind==="osc"){oscillators.push(item);continue}if(result.kind==="volume"){const hs:any=chart.current.addHistogramSeries({priceScaleId:"volume",priceFormat:{type:"volume"},color:cfg.color||"#777",priceLineVisible:false,lastValueVisible:false});hs.setData(d.map(x=>({time:x.time,value:x.volume,color:cfg.color||(x.close>=x.open?"#888":"#444")})));hs.priceScale().applyOptions({scaleMargins:{top:0.82,bottom:0}});indicatorSeries.current.push(hs);continue}for(const line of result.lines||[]){const ls:any=chart.current.addLineSeries({priceScaleId:"right",color:cfg.color||line.color,lineWidth:lineWidth(cfg.width),priceLineVisible:false,lastValueVisible:false});ls.setData(line.values.map((v:number|null,i:number)=>v==null?null:{time:d[i].time,value:v}).filter(Boolean));indicatorSeries.current.push(ls)}}
 if(!wasUserPositioned&&firstLoad){const visibleBars=Math.min(100,d.length);ts.applyOptions({rightOffset:3,minBarSpacing:1});ts.setVisibleRange({from:d[Math.max(0,d.length-visibleBars)].time,to:d[d.length-1].time});} else if(before){ts.setVisibleRange(before)}
 firstLoad=false;await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));if(!panesEl.current)return;for(const item of oscillators){const cfg:any=cfgs[item.id]||cfgs[item.name]||{};const host=panesEl.current.querySelector(`[data-indicator-pane="${CSS.escape(item.id)}"]`) as HTMLDivElement|null;if(!host)continue;const l=document.documentElement.classList.contains("light");const pc=createChart(host,{width:Math.max(1,host.clientWidth),height:125,layout:{background:{color:l?"#fff":"#000"},textColor:l?"#111":"#fff"},grid:{vertLines:{color:l?"#e5e5e5":"#1a1a1a"},horzLines:{color:l?"#e5e5e5":"#1a1a1a"}},rightPriceScale:{borderColor:l?"#d0d0d0":"#222",scaleMargins:{top:0.12,bottom:0.12},minimumWidth:64},timeScale:{visible:false}});const result:any=calculateIndicator(item.name,d,cfg);for(const line of result.lines||[]){const ls:any=pc.addLineSeries({color:cfg.color||line.color,lineWidth:lineWidth(cfg.width),priceLineVisible:false,lastValueVisible:true});ls.setData(line.values.map((v:number|null,i:number)=>v==null?null:{time:d[i].time,value:v}).filter(Boolean))}pc.timeScale().fitContent();paneCharts.current.push(pc)}}catch(e){console.error(e)}};load();const refreshId=window.setInterval(load,1000);return()=>{stop=true;window.clearInterval(refreshId)}},[symbol,timeframe,indicators.map(x=>x.id).join("|"),indicatorVersion,height]);
 const changeTimeframe=(tf:string)=>{if(tf!==timeframe)onTimeframeChange?.(tf)};
 return <div className="w-full h-full relative border border-[#1a1a1a] bg-black select-none overflow-hidden"><div className="absolute top-2 left-2 z-[70] flex items-center gap-1"><button onPointerDown={e=>e.stopPropagation()} onClick={e=>{e.stopPropagation();onSymbolClick?.()}} className="text-xs bg-black/80 px-2 py-1 rounded border border-[#333] text-white">{symbol}</button><div onPointerDown={e=>e.stopPropagation()} onClick={e=>e.stopPropagation()} className="flex items-center gap-1"><IndicatorMenu/></div></div><div className="absolute top-2 right-2 z-[60] pointer-events-auto flex items-center gap-1"><div onPointerDown={e=>e.stopPropagation()} onClick={e=>e.stopPropagation()} className="rounded-md bg-black/80 border border-[#333] px-1 py-1 shadow-lg"><TimeframeSelector value={timeframe} onChange={changeTimeframe}/></div></div>{countdownTop!==null&&<div className="absolute right-1 z-[55] rounded-sm bg-black/90 border border-white/50 px-1.5 py-0.5 text-[10px] font-mono font-bold text-white tabular-nums pointer-events-none shadow-[0_0_8px_rgba(255,255,255,0.35)]" style={{top:countdownTop}} title="Time remaining in current candle">{formatCountdown(countdown)}</div>}<div ref={el} style={{height}} className="w-full"/><div ref={panesEl} className="w-full">{indicators.map((item)=>(OSCILLATORS.includes(item.name)?<div key={item.id} className="relative border-t border-[#222]" style={{height:125}} data-indicator-pane={item.id}><span className="absolute left-2 top-1 z-10 text-[10px] text-[#aaa] bg-black/60 px-1 rounded">{item.name}</span></div>:null))}</div></div>;
}