"use client";
import {useEffect,useRef} from "react";
import {createChart,IChartApi,ISeriesApi,CandlestickData} from "lightweight-charts";
interface Props{symbol:string;timeframe:string;height?:number;onSymbolClick?:()=>void}
const intervals:Record<string,string>={"1m":"1m","5m":"5m","15m":"15m","1H":"1h","4H":"4h","1D":"1d"};
const colors=()=>{if(typeof window==="undefined")return{up:"#fff",down:"#666"};try{const p=JSON.parse(localStorage.getItem("jk-candle-colors")||"null");if(p?.up&&p?.down)return p}catch{}return{up:"#fff",down:"#666"}};
export function ChartPane({symbol,timeframe,height=400,onSymbolClick}:Props){
 const el=useRef<HTMLDivElement>(null),chart=useRef<IChartApi|null>(null),series=useRef<ISeriesApi<"Candlestick">|null>(null);
 useEffect(()=>{if(!el.current)return;const cc=colors(),light=document.documentElement.classList.contains("light");const c=createChart(el.current,{width:Math.max(1,el.current.clientWidth),height,layout:{background:{color:light?"#fff":"#000"},textColor:light?"#111":"#fff"},grid:{vertLines:{color:light?"#e5e5e5":"#1a1a1a"},horzLines:{color:light?"#e5e5e5":"#1a1a1a"}},crosshair:{mode:0},rightPriceScale:{borderColor:light?"#d0d0d0":"#222"},timeScale:{borderColor:light?"#d0d0d0":"#222",timeVisible:true}});const s=c.addCandlestickSeries({upColor:cc.up,downColor:cc.down,borderUpColor:cc.up,borderDownColor:cc.down,wickUpColor:cc.up,wickDownColor:cc.down});chart.current=c;series.current=s;const theme=()=>{const l=document.documentElement.classList.contains("light");c.applyOptions({layout:{background:{color:l?"#fff":"#000"},textColor:l?"#111":"#fff"},grid:{vertLines:{color:l?"#e5e5e5":"#1a1a1a"},horzLines:{color:l?"#e5e5e5":"#1a1a1a"}}})};const col=()=>{const x=colors();s.applyOptions({upColor:x.up,downColor:x.down,borderUpColor:x.up,borderDownColor:x.down,wickUpColor:x.up,wickDownColor:x.down})};const mo=new MutationObserver(theme);mo.observe(document.documentElement,{attributes:true,attributeFilter:["class"]});const ro=new ResizeObserver(()=>c.applyOptions({width:Math.max(1,el.current?.clientWidth||1),height}));ro.observe(el.current);window.addEventListener("jk-candle-colors-changed",col);return()=>{mo.disconnect();ro.disconnect();window.removeEventListener("jk-candle-colors-changed",col);c.remove();chart.current=null;series.current=null}},[height]);
 useEffect(()=>{let stop=false;const load=async()=>{if(!series.current)return;try{const r=await fetch(`https://api.binance.com/api/v3/klines?symbol=${symbol}&interval=${intervals[timeframe]||"15m"}&limit=300`,{cache:"no-store"});const raw=await r.json();if(!stop&&Array.isArray(raw)&&raw.length){const d:CandlestickData[]=raw.map((k:any)=>({time:Math.floor(k[0]/1000) as any,open:+k[1],high:+k[2],low:+k[3],close:+k[4]}));series.current?.setData(d);chart.current?.timeScale().fitContent()}}catch(e){console.error(e)}};load();return()=>{stop=true}},[symbol,timeframe]);
 return <div className="w-full h-full relative border border-[#1a1a1a] bg-black select-none"><div className="absolute top-2 left-2 z-50"><button onClick={e=>{e.stopPropagation();onSymbolClick?.()}} className="text-xs bg-black/70 px-2 py-1 rounded border border-[#333] text-white">{symbol} · {timeframe}</button></div><div ref={el} className="w-full h-full"/></div>;
}
