"use client";
import {useEffect,useRef,useState,type PointerEvent} from "react";
import {createChart,IChartApi,ISeriesApi,CandlestickData,Time} from "lightweight-charts";
import {Wrench,Trash2,X} from "lucide-react";
interface Props{symbol:string;timeframe:string;height?:number;onSymbolClick?:()=>void}
type P={time:number;price:number}; type D={tool:string;a:P;b:P}; type E={index:number;mode:"move"|"resizeA"|"resizeB";start:{x:number;y:number};orig:D};
const intervals:Record<string,string>={"1m":"1m","5m":"5m","15m":"15m","1H":"1h","4H":"4h","1D":"1d"};
const TOOLS=["Trend line","Horizontal line","Vertical line","Ray","Rectangle","Fibonacci Retracement"];
const DEF=[0,.236,.382,.5,.618,.786,1]; const CE="jk-candle-colors-changed",FE="jk-fib-settings-changed";
const colors=()=>{if(typeof window==="undefined")return{up:"#fff",down:"#666"};try{const p=JSON.parse(localStorage.getItem("jk-candle-colors")||"null");if(p?.up&&p?.down)return p}catch{}return{up:"#fff",down:"#666"}};
const fibs=()=>{if(typeof window==="undefined")return DEF;try{const p=JSON.parse(localStorage.getItem("jk-fib-levels")||"null");if(Array.isArray(p)&&p.length)return p.map(Number).filter(Number.isFinite)}catch{}return DEF};
export function ChartPane({symbol,timeframe,height=400,onSymbolClick}:Props){
 const el=useRef<HTMLDivElement>(null),chart=useRef<IChartApi|null>(null),series=useRef<ISeriesApi<"Candlestick">|null>(null);
 const [tool,setTool]=useState<string|null>(null),[tools,setTools]=useState(false),[fib,setFib]=useState(fibs()),[showFib,setShowFib]=useState(false);
 const [drawings,setDrawings]=useState<D[]>([]),[draft,setDraft]=useState<P|null>(null),[draftPx,setDraftPx]=useState<{x:number;y:number}|null>(null),[cursor,setCursor]=useState<{x:number;y:number}|null>(null);
 const [active,setActive]=useState<number|null>(null),[edit,setEdit]=useState<E|null>(null),gesture=useRef<"idle"|"start"|"end">("idle"),lastPx=useRef<{x:number;y:number}|null>(null);
 const point=(e:{currentTarget:Element;clientX:number;clientY:number})=>{const r=e.currentTarget.getBoundingClientRect();return{x:Math.max(0,Math.min(r.width,e.clientX-r.left)),y:Math.max(0,Math.min(r.height,e.clientY-r.top))}};
 const toAnchor=(p:{x:number;y:number}):P|null=>{const c=chart.current,s=series.current;if(!c||!s)return null;const t=c.timeScale().coordinateToTime(p.x);const price=s.coordinateToPrice(p.y);if(t==null||price==null)return null;return{time:typeof t==="number"?t:Number(t),price:Number(price)}};
 const px=(p:P)=>{const c=chart.current,s=series.current;if(!c||!s)return null;const x=c.timeScale().timeToCoordinate(p.time as Time),y=s.priceToCoordinate(p.price);if(x==null||y==null)return null;return{x,y}};
 const finish=()=>{gesture.current="idle";setTool(null);setDraft(null);setDraftPx(null);setCursor(null)};
 useEffect(()=>{if(!el.current)return;const cc=colors(),light=document.documentElement.classList.contains("light");const c=createChart(el.current,{width:Math.max(1,el.current.clientWidth),height,layout:{background:{color:light?"#fff":"#000"},textColor:light?"#111":"#fff"},grid:{vertLines:{color:light?"#e5e5e5":"#1a1a1a"},horzLines:{color:light?"#e5e5e5":"#1a1a1a"}},crosshair:{mode:0},rightPriceScale:{borderColor:light?"#d0d0d0":"#222"},timeScale:{borderColor:light?"#d0d0d0":"#222",timeVisible:true}});const s=c.addCandlestickSeries({upColor:cc.up,downColor:cc.down,borderUpColor:cc.up,borderDownColor:cc.down,wickUpColor:cc.up,wickDownColor:cc.down});chart.current=c;series.current=s;const theme=()=>{const l=document.documentElement.classList.contains("light");c.applyOptions({layout:{background:{color:l?"#fff":"#000"},textColor:l?"#111":"#fff"},grid:{vertLines:{color:l?"#e5e5e5":"#1a1a1a"},horzLines:{color:l?"#e5e5e5":"#1a1a1a"}}})};const col=()=>{const x=colors();s.applyOptions({upColor:x.up,downColor:x.down,borderUpColor:x.up,borderDownColor:x.down,wickUpColor:x.up,wickDownColor:x.down})};const fc=()=>setFib(fibs());const mo=new MutationObserver(theme);mo.observe(document.documentElement,{attributes:true,attributeFilter:["class"]});const ro=new ResizeObserver(()=>c.applyOptions({width:Math.max(1,el.current?.clientWidth||1),height}));ro.observe(el.current);window.addEventListener(CE,col);window.addEventListener(FE,fc);return()=>{mo.disconnect();ro.disconnect();window.removeEventListener(CE,col);window.removeEventListener(FE,fc);c.remove();chart.current=null;series.current=null}},[height]);
 useEffect(()=>{let stop=false;const load=async()=>{if(!series.current)return;try{const r=await fetch(`https://api.binance.com/api/v3/klines?symbol=${symbol}&interval=${intervals[timeframe]||"15m"}&limit=300`,{cache:"no-store"});const raw=await r.json();if(!stop&&Array.isArray(raw)&&raw.length){const d:CandlestickData[]=raw.map((k:any)=>({time:Math.floor(k[0]/1000) as any,open:+k[1],high:+k[2],low:+k[3],close:+k[4]}));series.current?.setData(d);chart.current?.timeScale().fitContent();setDrawings([]);setActive(null)}}catch(e){console.error(e)}};load();return()=>{stop=true}},[symbol,timeframe]);
 useEffect(()=>{if(!tool)return;gesture.current="idle";setDraft(null);setDraftPx(null);const c=chart.current;c?.applyOptions({handleScroll:false,handleScale:false});return()=>{c?.applyOptions({handleScroll:true,handleScale:true})}},[tool]);
 const down=(e:PointerEvent<HTMLDivElement>)=>{if(!tool||tools||showFib)return;e.preventDefault();e.stopPropagation();const p=point(e);setCursor(p);lastPx.current=p;if(gesture.current==="idle"){gesture.current="start";setDraftPx(p);const a=toAnchor(p);if(a)setDraft(a);e.currentTarget.setPointerCapture?.(e.pointerId)}else if(gesture.current==="end"){const a=draft,b=toAnchor(p);if(a&&b){setDrawings(x=>[...x,{tool,a,b}]);finish()}}};
 const move=(e:PointerEvent<HTMLDivElement>)=>{if(!tool)return;const p=point(e);setCursor(p);lastPx.current=p;if(gesture.current==="start"){const a=toAnchor(p);if(a)setDraft(a);setDraftPx(p)}if(gesture.current==="end")setDraftPx(p)};
 const up=(e:PointerEvent<HTMLDivElement>)=>{if(!tool||gesture.current!=="start")return;e.preventDefault();const p=point(e),a=draft||toAnchor(p);if(!a)return;gesture.current="end";setDraft(a);setDraftPx(p)};
 const begin=(i:number,mode:E["mode"],e:PointerEvent<SVGElement>)=>{e.preventDefault();e.stopPropagation();const p=point(e),d=drawings[i];setActive(i);setEdit({index:i,mode,start:p,orig:d});e.currentTarget.setPointerCapture?.(e.pointerId)};
 const editMove=(e:PointerEvent<SVGElement>)=>{if(!edit)return;const p=point(e),op=px(edit.orig.a),oq=px(edit.orig.b);if(!op||!oq)return;const dx=p.x-edit.start.x,dy=p.y-edit.start.y;const convert=(old:P,oldPx:{x:number;y:number}):P=>toAnchor({x:oldPx.x+dx,y:oldPx.y+dy})||old;setDrawings(ds=>ds.map((d,i)=>i!==edit.index?d:edit.mode==="resizeA"?{...d,a:convert(edit.orig.a,op)}:edit.mode==="resizeB"?{...d,b:convert(edit.orig.b,oq)}:{...d,a:convert(edit.orig.a,op),b:convert(edit.orig.b,oq)}))};
 const shape=(d:D,i:number,interactive=false)=>{const a=px(d.a),b=px(d.b);if(!a||!b)return null;const hit=(m:E["mode"])=>interactive?{onPointerDown:(e:PointerEvent<SVGElement>)=>begin(i,m,e),style:{pointerEvents:"stroke" as const}}:{};if(d.tool==="Horizontal line")return <line key={i} x1="0" y1={a.y} x2="100%" y2={a.y} stroke={interactive?"transparent":"currentColor"} strokeWidth={interactive?18:1.5}{...hit("resizeA")}/>;if(d.tool==="Vertical line")return <line key={i} x1={a.x} y1="0" x2={a.x} y2="100%" stroke={interactive?"transparent":"currentColor"} strokeWidth={interactive?18:1.5}{...hit("resizeA")}/>;if(d.tool==="Rectangle")return <rect key={i} x={Math.min(a.x,b.x)} y={Math.min(a.y,b.y)} width={Math.abs(b.x-a.x)} height={Math.abs(b.y-a.y)} fill="none" stroke={interactive?"transparent":"currentColor"} strokeWidth={interactive?18:1.5}{...hit("move")}/>;if(d.tool==="Fibonacci Retracement"){return <g key={i}><line x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke={interactive?"transparent":"currentColor"} strokeWidth={interactive?18:1}/>{!interactive&&fib.map((l,j)=>{const y=a.y+(b.y-a.y)*l;return <g key={j}><line x1={a.x} y1={y} x2={b.x} y2={y} stroke="currentColor" opacity=".65"/><text x={b.x+5} y={y-3} fontSize="10" fill="currentColor">{l*100}%</text></g>})}{interactive&&<line x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke="transparent" strokeWidth="18" style={{pointerEvents:"stroke"}} onPointerDown={e=>begin(i,"move",e)}/>}</g>};if(d.tool==="Ray"){const vx=b.x-a.x,vy=b.y-a.y,t=4;return <line key={i} x1={a.x} y1={a.y} x2={a.x+vx*t} y2={a.y+vy*t} stroke={interactive?"transparent":"currentColor"} strokeWidth={interactive?18:1.5}{...hit("move")}/>};return <line key={i} x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke={interactive?"transparent":"currentColor"} strokeWidth={interactive?18:1.5}{...hit("move")}/>};
 const activeD=active!=null?drawings[active]:null,ap=activeD?px(activeD.a):null,bp=activeD?px(activeD.b):null;
 const saveFib=(v:number[])=>{const n=v.map(Number).filter(Number.isFinite).sort((a,b)=>a-b);setFib(n);try{localStorage.setItem("jk-fib-levels",JSON.stringify(n));window.dispatchEvent(new Event(FE))}catch{}};
 return <div className="w-full h-full relative border border-[#1a1a1a] bg-black select-none" style={{touchAction:tool?"none":"auto"}} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={()=>{gesture.current="idle";setDraft(null);setDraftPx(null)}}>
  <div className="absolute top-2 left-2 z-50 flex gap-1"><button onClick={e=>{e.stopPropagation();onSymbolClick?.()}} className="text-xs bg-black/70 px-2 py-1 rounded border border-[#333]">{symbol} · {timeframe}</button><button onClick={e=>{e.stopPropagation();setTools(v=>!v);setTool(null)}} className="w-7 h-7 flex items-center justify-center rounded border border-[#333] bg-black/70 text-[#aaa]"><Wrench size={14}/></button></div>
  <div ref={el} className="w-full h-full"/>
  {tool&&cursor&&<div className="absolute inset-0 z-20 pointer-events-none"><div className="absolute top-0 bottom-0 w-px bg-white/80" style={{left:cursor.x}}/><div className="absolute left-0 right-0 h-px bg-white/80" style={{top:cursor.y}}/><div className="absolute w-3 h-3 rounded-full border-2 border-white bg-black -translate-x-1/2 -translate-y-1/2" style={{left:cursor.x,top:cursor.y}}/></div>}
  <svg className="absolute inset-0 z-10 w-full h-full pointer-events-none text-white">{drawings.map((d,i)=>shape(d,i))}{draft&&draftPx&&shape({tool:tool||"Trend line",a:draft,b:toAnchor(draftPx)||draft},9999)}</svg>
  {!tool&&drawings.length>0&&<svg className="absolute inset-0 z-[18] w-full h-full pointer-events-none text-white" onPointerMove={editMove} onPointerUp={()=>setEdit(null)}>{drawings.map((d,i)=>shape(d,i,true))}</svg>}
  {activeD&&ap&&bp&&<><svg className="absolute inset-0 z-30 w-full h-full pointer-events-none"><circle cx={ap.x} cy={ap.y} r="7" fill="black" stroke="white" strokeWidth="2" style={{pointerEvents:"auto"}} onPointerDown={e=>begin(active!,"resizeA",e)}/>{activeD.tool!=="Horizontal line"&&activeD.tool!=="Vertical line"&&<circle cx={bp.x} cy={bp.y} r="7" fill="black" stroke="white" strokeWidth="2" style={{pointerEvents:"auto"}} onPointerDown={e=>begin(active!,"resizeB",e)}/>}</svg><div className="absolute z-50 top-11 right-2 flex gap-1 rounded-lg border border-[#333] bg-[#0a0a0a] p-1"><span className="text-[10px] text-[#888] px-1 py-1">Drag handles</span><button className="text-xs px-2 text-white" onClick={()=>setActive(null)}>Done</button><button className="text-xs px-2 text-red-300" onClick={()=>{setDrawings(d=>d.filter((_,i)=>i!==active));setActive(null)}}><Trash2 size={12}/></button><button className="p-1 text-[#888]" onClick={()=>setActive(null)}><X size={12}/></button></div></>}
  {draft&&<div className="absolute bottom-2 left-1/2 -translate-x-1/2 z-30 rounded bg-black/80 border border-[#333] px-2 py-1 text-[11px] text-white pointer-events-none">Drag to start → release → drag to end → release</div>}
  {tools&&<div className="absolute top-11 left-2 z-50 w-56 rounded-lg border border-[#333] bg-[#0a0a0a] p-2 shadow-2xl"><div className="px-2 py-1 text-xs text-[#888]">Drawing tools</div>{TOOLS.map(t=><button key={t} onClick={()=>{setTools(false);setActive(null);setTool(t)}} className="w-full rounded px-2 py-2 text-left text-sm text-white hover:bg-[#1a1a1a]">{t}</button>)}<button onClick={()=>{setShowFib(true);setTools(false)}} className="w-full px-2 py-2 text-left text-sm text-[#aaa]">Fibonacci Settings</button><button onClick={()=>{setDrawings([]);setActive(null)}} className="w-full px-2 py-2 text-left text-sm text-[#aaa]">Clear drawings</button></div>}
  {showFib&&<div className="absolute top-11 left-2 z-[60] w-64 rounded-lg border border-[#333] bg-[#0a0a0a] p-3"><div className="text-sm font-semibold text-white mb-2">Fibonacci Settings</div>{fib.map((l,i)=><div key={i} className="flex gap-2 mb-2"><input type="number" step=".001" value={l} onChange={e=>{const n=[...fib];n[i]=Number(e.target.value);setFib(n)}} className="w-full bg-black border border-[#333] rounded px-2 py-1 text-white"/><button onClick={()=>setFib(fib.filter((_,j)=>j!==i))} className="text-[#888]">×</button></div>)}<div className="flex gap-2"><button onClick={()=>setFib([...fib,1.618])} className="flex-1 border border-[#333] py-1 text-xs text-white">+1.618</button><button onClick={()=>saveFib(fib)} className="flex-1 bg-white text-black py-1 text-xs">Save</button></div><button onClick={()=>setShowFib(false)} className="w-full mt-2 border border-[#333] py-1 text-xs text-[#aaa]">Done</button></div>}
 </div>;
}