export type Candle={time:any;open:number;high:number;low:number;close:number;volume:number};
export type IndicatorConfig=Record<string,number>;
const sma=(v:(number|null)[],n:number)=>(v.map((_,i)=>{if(i+1<n)return null;const a=v.slice(i-n+1,i+1);if(a.some(x=>x==null))return null;return (a as number[]).reduce((x,y)=>x+y,0)/n}));
const ema=(v:(number|null)[],n:number)=>{const out:(number|null)[]=Array(v.length).fill(null);const first=v.findIndex(x=>x!=null);if(first<0||v.length-first<n)return out;let sum=0;for(let i=first;i<first+n;i++)sum+=v[i] as number;let e=sum/n;out[first+n-1]=e;const k=2/(n+1);for(let i=first+n;i<v.length;i++){const x=v[i];if(x==null)continue;e=(x as number)*k+e*(1-k);out[i]=e}return out};
const tr=(c:Candle[])=>c.map((x,i)=>i?Math.max(x.high-x.low,Math.abs(x.high-c[i-1].close),Math.abs(x.low-c[i-1].close)):x.high-x.low);
const rma=(v:(number|null)[],n:number)=>{const out:(number|null)[]=Array(v.length).fill(null);let start=v.findIndex(x=>x!=null);while(start>=0&&start+n<=v.length){const a=v.slice(start,start+n);if(a.some(x=>x==null))return out;let avg=(a as number[]).reduce((x,y)=>x+y,0)/n;out[start+n-1]=avg;const k=1/n;for(let i=start+n;i<v.length;i++){if(v[i]==null)continue;avg=((avg*(n-1))+(v[i] as number))*k;out[i]=avg}break}return out};
export function calculateIndicator(name:string,c:Candle[],cfg:IndicatorConfig){const close=c.map(x=>x.close),n=Math.max(1,Math.round(cfg.length||14));
 if(name==="Moving Average"||name==="SMA")return{kind:"overlay",lines:[{name,color:"#00bcd4",values:sma(close,n)}]};
 if(name==="EMA")return{kind:"overlay",lines:[{name,color:"#ff9800",values:ema(close,n)}]};
 if(name==="Bollinger Bands"){const mid=sma(close,n),sd=close.map((_,i)=>{if(i+1<n||mid[i]==null)return null;const a=close.slice(i-n+1,i+1),m=mid[i] as number;return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/n)}),m=Number.isFinite(cfg.mult)?cfg.mult:2;return{kind:"overlay",lines:[{name:"BB Basis",color:"#999",values:mid},{name:"BB Upper",color:"#fff",values:mid.map((x,i)=>x==null||sd[i]==null?null:x+m*(sd[i] as number))},{name:"BB Lower",color:"#fff",values:mid.map((x,i)=>x==null||sd[i]==null?null:x-m*(sd[i] as number))}]};}
 if(name==="VWAP"){let pv=0,v=0;return{kind:"overlay",lines:[{name,color:"#e91e63",values:c.map(x=>{const tp=(x.high+x.low+x.close)/3;pv+=tp*x.volume;v+=x.volume;return pv/v})}]};}
 if(name==="Volume")return{kind:"volume",values:c.map(x=>x.volume)};
 if(name==="Volume Profile"){const poc=c.reduce((best,x)=>x.volume>best.volume?x:best,c[0]);return{kind:"overlay",lines:[{name:"VP POC",color:"#9c27b0",values:c.map(()=>poc.close)}],meta:`POC ${poc.close.toFixed(2)}`};}
 if(name==="RSI"){const gains=c.map((x,i)=>i?Math.max(0,x.close-c[i-1].close):0),loss=c.map((x,i)=>i?Math.max(0,c[i-1].close-x.close):0),g=rma(gains,n),l=rma(loss,n);return{kind:"osc",lines:[{name:"RSI",color:"#00e676",values:g.map((x,i)=>x==null||l[i]==null?null:l[i]===0?100:100-100/(1+(x as number)/(l[i] as number)))}],min:0,max:100};}
 if(name==="MACD"){const fast=Math.max(2,Math.round(cfg.fast||12)),slow=Math.max(fast+1,Math.round(cfg.slow||26)),sig=Math.max(2,Math.round(cfg.signal||9)),f=ema(close,fast),s=ema(close,slow),m=f.map((x,i)=>x==null||s[i]==null?null:x-(s[i] as number)),sg=ema(m,sig);return{kind:"osc",lines:[{name:"MACD",color:"#29b6f6",values:m},{name:"Signal",color:"#ffb300",values:sg},{name:"Histogram",color:"#aaa",values:m.map((x,i)=>x==null||sg[i]==null?null:x-(sg[i] as number))}]};}
 if(name==="Stochastic"){const k=c.map((x,i)=>{if(i+1<n)return null;const a=c.slice(i-n+1,i+1),hi=Math.max(...a.map(z=>z.high)),lo=Math.min(...a.map(z=>z.low));return hi===lo?50:(x.close-lo)/(hi-lo)*100}),d=sma(k,Math.max(1,Math.round(cfg.smooth||3)));return{kind:"osc",lines:[{name:"%K",color:"#42a5f5",values:k},{name:"%D",color:"#ef5350",values:d}],min:0,max:100};}
 if(name==="ATR")return{kind:"osc",lines:[{name:"ATR",color:"#ff9800",values:rma(tr(c),n)}]};
 if(name==="ADX"){const plus:number[]=Array(c.length).fill(0),minus:number[]=Array(c.length).fill(0);for(let i=1;i<c.length;i++){const up=c[i].high-c[i-1].high,down=c[i-1].low-c[i].low;plus[i]=up>down&&up>0?up:0;minus[i]=down>up&&down>0?down:0}const atr=rma(tr(c),n),p=rma(plus,n),m=rma(minus,n),dx=atr.map((a,i)=>a==null||p[i]==null||m[i]==null?null:100*Math.abs((p[i] as number)-(m[i] as number))/Math.max((p[i] as number)+(m[i] as number),1e-12));return{kind:"osc",lines:[{name:"ADX",color:"#ab47bc",values:rma(dx,n)}],min:0,max:100};}
 if(name==="CCI"){const tp=c.map(x=>(x.high+x.low+x.close)/3),m=sma(tp,n),vals=tp.map((x,i)=>{if(m[i]==null)return null;const a=tp.slice(i-n+1,i+1),dev=a.reduce((s,z)=>s+Math.abs(z-(m[i] as number)),0)/n;return dev?(x-(m[i] as number))/(0.015*dev):0});return{kind:"osc",lines:[{name:"CCI",color:"#26c6da",values:vals}]};}
 if(name==="Williams %R"){const vals=c.map((x,i)=>{if(i+1<n)return null;const a=c.slice(i-n+1,i+1),hi=Math.max(...a.map(z=>z.high)),lo=Math.min(...a.map(z=>z.low));return hi===lo?-50:-100*(hi-x.close)/(hi-lo)});return{kind:"osc",lines:[{name:"Williams %R",color:"#66bb6a",values:vals}],min:-100,max:0};}
 return null;
}
