export type Candle={time:any;open:number;high:number;low:number;close:number;volume:number};
export type IndicatorConfig=Record<string,number>;

const sma=(v:number[],n:number)=>v.map((_,i)=>i+1<n?null:v.slice(i-n+1,i+1).reduce((a,b)=>a+b,0)/n);
const ema=(v:number[],n:number)=>{const out:(number|null)[]=Array(v.length).fill(null);if(v.length<n)return out;let e=v.slice(0,n).reduce((a,b)=>a+b,0)/n;out[n-1]=e;const k=2/(n+1);for(let i=n;i<v.length;i++){e=v[i]*k+e*(1-k);out[i]=e}return out};
const tr=(c:Candle[])=>c.map((x,i)=>i?Math.max(x.high-x.low,Math.abs(x.high-c[i-1].close),Math.abs(x.low-c[i-1].close)):x.high-x.low);
const rma=(v:number[],n:number)=>{const out:(number|null)[]=Array(v.length).fill(null);if(v.length<n)return out;let a=v.slice(0,n).reduce((x,y)=>x+y,0)/n;out[n-1]=a;for(let i=n;i<v.length;i++){a=(a*(n-1)+v[i])/n;out[i]=a}return out};
export function calculateIndicator(name:string,c:Candle[],cfg:IndicatorConfig){const close=c.map(x=>x.close), n=Math.max(1,Math.round(cfg.length||14));
 if(name==="Moving Average"||name==="SMA")return {kind:"overlay",lines:[{name:name,color:"#00bcd4",values:sma(close,n)}]};
 if(name==="EMA")return {kind:"overlay",lines:[{name,color:"#ff9800",values:ema(close,n)}]};
 if(name==="Bollinger Bands"){const mid=sma(close,n);const sd=close.map((_,i)=>{if(i+1<n)return null;const a=close.slice(i-n+1,i+1),m=mid[i] as number;return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/n)});const m=cfg.mult||2;return{kind:"overlay",lines:[{name:"BB Basis",color:"#999",values:mid},{name:"BB Upper",color:"#fff",values:mid.map((x,i)=>x==null||sd[i]==null?null:x+m*(sd[i] as number))},{name:"BB Lower",color:"#fff",values:mid.map((x,i)=>x==null||sd[i]==null?null:x-m*(sd[i] as number))}]};}
 if(name==="VWAP"){let pv=0,v=0;const vals=c.map(x=>{const tp=(x.high+x.low+x.close)/3;pv+=tp*x.volume;v+=x.volume;return v?pv/v:tp});return{kind:"overlay",lines:[{name,color:"#e91e63",values:vals}]};}
 if(name==="Volume")return{kind:"volume",values:c.map(x=>x.volume)};
 if(name==="Volume Profile"){const total=c.reduce((s,x)=>s+x.volume,0)||1;const poc=c.reduce((best,x)=>x.volume>best.volume?x:best,c[0]);return{kind:"overlay",lines:[{name:"VP POC",color:"#9c27b0",values:c.map(()=>poc?.close??0)}],meta:`POC ${poc?.close?.toFixed(2)??"-"}`};}
 if(name==="RSI"){const gains=c.map((x,i)=>i?Math.max(0,x.close-c[i-1].close):0),loss=c.map((x,i)=>i?Math.max(0,c[i-1].close-x.close):0),g=rma(gains,n),l=rma(loss,n);return{kind:"osc",lines:[{name:"RSI",color:"#00e676",values:g.map((x,i)=>x==null||l[i]==null?null:(l[i]===0?100:100-100/(1+x/(l[i] as number))))}],min:0,max:100};}
 if(name==="MACD"){const fast=Math.max(2,Math.round(cfg.fast||12)),slow=Math.max(fast+1,Math.round(cfg.slow||26)),sig=Math.max(2,Math.round(cfg.signal||9));const f=ema(close,fast),s=ema(close,slow);const m=f.map((x,i)=>x==null||s[i]==null?null:x-(s[i] as number));const clean=m.map(x=>x??0),sg=ema(clean,sig);return{kind:"osc",lines:[{name:"MACD",color:"#29b6f6",values:m},{name:"Signal",color:"#ffb300",values:sg},{name:"Histogram",color:"#aaa",values:m.map((x,i)=>x==null||sg[i]==null?null:x-(sg[i] as number))}],min:null,max:null};}
 if(name==="Stochastic"){const k=c.map((x,i)=>{if(i+1<n)return null;const a=c.slice(i-n+1,i+1),hi=Math.max(...a.map(z=>z.high)),lo=Math.min(...a.map(z=>z.low));return hi===lo?50:((x.close-lo)/(hi-lo))*100});const d=sma(k.map(x=>x??0),Math.max(1,Math.round(cfg.smooth||3)));return{kind:"osc",lines:[{name:"%K",color:"#42a5f5",values:k},{name:"%D",color:"#ef5350",values:d}],min:0,max:100};}
 if(name==="ATR"){return{kind:"osc",lines:[{name:"ATR",color:"#ff9800",values:rma(tr(c),n)}]};}
 if(name==="ADX"){const trs=tr(c),plus=c.map((x,i)=>i?Math.max(0,x.high-c[i-1].high-(x.low-c[i-1].low> x.high-c[i-1].high?0:Math.max(0,x.low-c[i-1].low))):0),minus=c.map((x,i)=>i?Math.max(0,c[i-1].low-x.low-(c[i-1].high-x.high> x.low-c[i-1].low?0:Math.max(0,c[i-1].high-x.high))):0),atr=rma(trs,n),p=rma(plus,n),m=rma(minus,n);const dx=atr.map((a,i)=>a==null||p[i]==null||m[i]==null?null:((100*Math.abs((p[i] as number)-(m[i] as number))/((p[i] as number)+(m[i] as number)||1))));return{kind:"osc",lines:[{name:"ADX",color:"#ab47bc",values:rma(dx.map(x=>x??0),n)}],min:0,max:100};}
 if(name==="CCI"){const tp=c.map(x=>(x.high+x.low+x.close)/3),m=sma(tp,n);const vals=tp.map((x,i)=>{if(m[i]==null)return null;const a=tp.slice(i-n+1,i+1),dev=a.reduce((s,z)=>s+Math.abs(z-(m[i] as number)),0)/n;return dev?((x-(m[i] as number))/(0.015*dev)):0});return{kind:"osc",lines:[{name:"CCI",color:"#26c6da",values:vals}]};}
 if(name==="Williams %R"){const vals=c.map((x,i)=>{if(i+1<n)return null;const a=c.slice(i-n+1,i+1),hi=Math.max(...a.map(z=>z.high)),lo=Math.min(...a.map(z=>z.low));return hi===lo?-50:-100*(hi-x.close)/(hi-lo)});return{kind:"osc",lines:[{name:"Williams %R",color:"#66bb6a",values:vals}],min:-100,max:0};}
 return null;
}
