"use client";
import {useEffect,useState} from "react";
import {Settings2,X} from "lucide-react";
const defaults:Record<string,Record<string,number>>={"Moving Average":{length:20},EMA:{length:20},SMA:{length:20},"Bollinger Bands":{length:20,mult:2},VWAP:{},RSI:{length:14},MACD:{fast:12,slow:26,signal:9},Stochastic:{length:14,smooth:3},ATR:{length:14},ADX:{length:14},CCI:{length:20},"Williams %R":{length:14},Volume:{},"Volume Profile":{}};
type Item={id:string;name:string};
const read=():Item[]=>{try{const a=JSON.parse(localStorage.getItem("jk-indicators")||"[]");return Array.isArray(a)?a.map((x:any,i:number)=>typeof x==="string"?{id:`${x}-${i+1}`,name:x}:x&&x.id&&x.name?x:null).filter(Boolean):[]}catch{return[]}};
export function IndicatorMenu(){const[items,setItems]=useState<Item[]>([]),[edit,setEdit]=useState<Item|null>(null),[cfg,setCfg]=useState<Record<string,number>>({});useEffect(()=>{const fn=()=>setItems(read());fn();window.addEventListener("jk-indicators-changed",fn);return()=>window.removeEventListener("jk-indicators-changed",fn)},[]);
 const startEdit=(item:Item)=>{let saved:any={};try{const all=JSON.parse(localStorage.getItem("jk-indicator-settings")||"{}");saved=all[item.id]||all[item.name]||{}}catch{}setCfg({...defaults[item.name],...saved});setEdit(item)};
 const save=()=>{if(!edit)return;let all:any={};try{all=JSON.parse(localStorage.getItem("jk-indicator-settings")||"{}")}catch{}all[edit.id]=cfg;localStorage.setItem("jk-indicator-settings",JSON.stringify(all));window.dispatchEvent(new Event("jk-indicators-changed"));setEdit(null)};
 return <div className="relative flex items-center gap-1 flex-wrap">{items.map((item,i)=><div key={item.id} className="relative"><div className="flex items-center gap-1 rounded bg-black/80 border border-[#333] px-2 py-1"><span className="text-[11px] text-white">{item.name}{items.filter(x=>x.name===item.name).length>1&&<span className="text-[#777] ml-1">#{items.slice(0,i+1).filter(x=>x.name===item.name).length}</span>}</span><button onPointerDown={e=>e.stopPropagation()} onClick={e=>{e.stopPropagation();startEdit(item)}} title={`Edit ${item.name}`} className="text-[#aaa] hover:text-white"><Settings2 size={13}/></button></div>{edit?.id===item.id&&<div className="absolute left-0 top-9 z-[250] w-[min(300px,calc(100vw-24px))] rounded-xl border border-[#333] bg-[#080808] shadow-2xl p-4"><div className="flex items-center justify-between mb-3"><div className="font-medium text-sm">{edit.name} Settings</div><button onClick={()=>setEdit(null)} className="text-[#777]"><X size={15}/></button></div>{Object.keys(cfg).length>0?<><div className="grid grid-cols-2 gap-2">{Object.entries(cfg).map(([key,value])=><label key={key} className="text-[11px] text-[#777] capitalize">{key}<input type="number" min={1} step={key==="mult"?0.1:1} value={value} onChange={e=>setCfg(x=>({...x,[key]:Number(e.target.value)}))} className="mt-1 w-full rounded border border-[#333] bg-black px-2 py-2 text-sm text-white outline-none focus:border-white"/></label>)}</div><button onClick={save} className="w-full mt-3 rounded-md bg-white text-black py-2 text-sm font-medium">Apply Changes</button></>:<div className="text-xs text-[#777]">No numeric settings for this indicator.</div>}</div>}</div>)}</div>}
