"use client";
import {useEffect,useState} from "react";
import {ChevronDown,Settings2,X} from "lucide-react";
const defaults:Record<string,Record<string,number|string>>={"Moving Average":{length:20,color:"#00bcd4",width:2},EMA:{length:20,color:"#ff9800",width:2},SMA:{length:20,color:"#00bcd4",width:2},"Bollinger Bands":{length:20,mult:2,color:"#ffffff",width:2},VWAP:{color:"#e91e63",width:2},RSI:{length:14,color:"#00e676",width:2},MACD:{fast:12,slow:26,signal:9,color:"#29b6f6",width:2},Stochastic:{length:14,smooth:3,color:"#42a5f5",width:2},ATR:{length:14,color:"#ff9800",width:2},ADX:{length:14,color:"#ab47bc",width:2},CCI:{length:20,color:"#26c6da",width:2},"Williams %R":{length:14,color:"#66bb6a",width:2},Volume:{color:"#777777",width:2},"Volume Profile":{color:"#9c27b0",width:2}};
export function IndicatorMenu(){
 const[open,setOpen]=useState(false),[selected,setSelected]=useState<string[]>([]),[edit,setEdit]=useState<string|null>(null),[cfg,setCfg]=useState<Record<string,number|string>>({});
 useEffect(()=>{const read=()=>{try{const a=JSON.parse(localStorage.getItem("jk-indicators")||"[]");setSelected(Array.isArray(a)?a:[])}catch{setSelected([])}};read();window.addEventListener("jk-indicators-changed",read);return()=>window.removeEventListener("jk-indicators-changed",read)},[]);
 const startEdit=(name:string)=>{let saved:any={};try{const all=JSON.parse(localStorage.getItem("jk-indicator-settings")||"{}");saved=all[name]||{}}catch{}setCfg({...defaults[name],...saved});setEdit(name)};
 const save=()=>{if(!edit)return;let all:any={};try{all=JSON.parse(localStorage.getItem("jk-indicator-settings")||"{}")}catch{}all[edit]=cfg;localStorage.setItem("jk-indicator-settings",JSON.stringify(all));window.dispatchEvent(new Event("jk-indicators-changed"));setEdit(null)};
 return <div className="relative">
  <button type="button" onClick={()=>setOpen(v=>!v)} className="h-9 px-3 rounded-md border border-[#333] bg-[#0a0a0a] text-sm text-white flex items-center gap-2 hover:border-white"><span>{selected.length?selected.join(" • "):"Indicators"}</span><ChevronDown size={14}/></button>
  {open&&<div className="absolute left-0 top-11 z-[200] w-[min(360px,calc(100vw-24px))] rounded-xl border border-[#333] bg-[#080808] shadow-2xl overflow-hidden">
   <div className="flex items-center justify-between px-4 py-3 border-b border-[#222]"><div><div className="font-medium">Indicator Settings</div><div className="text-[11px] text-[#666]">Edit selected indicators</div></div><button onClick={()=>{setOpen(false);setEdit(null)}} className="text-[#888] hover:text-white"><X size={17}/></button></div>
   <div className="p-2">{selected.length===0?<div className="px-3 py-5 text-center text-xs text-[#666]">No indicator selected.</div>:selected.map(name=><div key={name} className="flex items-center gap-2 rounded-lg px-3 py-2 bg-[#101010] mb-1.5"><span className="flex-1 text-sm text-white">{name}</span><button title={`Edit ${name}`} onClick={()=>startEdit(name)} className="w-8 h-8 flex items-center justify-center rounded border border-[#333] text-[#aaa] hover:text-white hover:border-white"><Settings2 size={15}/></button></div>)}</div>
   {edit&&<div className="border-t border-[#222] p-4 bg-[#0c0c0c]"><div className="flex items-center justify-between mb-3"><div className="font-medium text-sm">{edit} Settings</div><button onClick={()=>setEdit(null)} className="text-[#777]"><X size={15}/></button></div><div className="grid grid-cols-2 gap-2">{Object.entries(cfg).map(([key,value])=>key==="color"?<label key={key} className="col-span-2 text-[11px] text-[#777]">Color<input type="color" value={String(value)} onChange={e=>setCfg(x=>({...x,color:e.target.value}))} className="mt-1 w-full h-10 rounded border border-[#333] bg-black cursor-pointer"/></label>:<label key={key} className="text-[11px] text-[#777] capitalize">{key}<input type="number" min={1} step={key==="mult"?0.1:1} value={Number(value)} onChange={e=>setCfg(x=>({...x,[key]:Number(e.target.value)}))} className="mt-1 w-full rounded border border-[#333] bg-black px-2 py-2 text-sm text-white outline-none focus:border-white"/></label>)}</div><label className="block mt-3 text-[11px] text-[#777]">Line Thickness <span className="text-white">{Number(cfg.width)||2}px</span><input type="range" min={1} max={5} step={1} value={Number(cfg.width)||2} onChange={e=>setCfg(x=>({...x,width:Number(e.target.value)}))} className="mt-2 w-full"/></label><button onClick={save} className="w-full mt-3 rounded-md bg-white text-black py-2 text-sm font-medium">Apply Changes</button></div>}
  </div>}
 </div>;
}