"use client";
import {useEffect,useState} from "react";
import {Plus,Minus} from "lucide-react";
const defaultUp="#ffffff";const defaultDown="#666666";
const INDICATORS=["Moving Average","EMA","SMA","Bollinger Bands","VWAP","RSI","MACD","Stochastic","ATR","ADX","CCI","Williams %R","Volume","Volume Profile"];
type Item={id:string;name:string};
const normalize=(raw:any[]):Item[]=>raw.map((x:any,i:number)=>typeof x==="string"?{id:`${x}-${i+1}`,name:x}:x&&x.id&&x.name?x:null).filter(Boolean) as Item[];
export default function SettingsPage(){const[upColor,setUpColor]=useState(defaultUp),[downColor,setDownColor]=useState(defaultDown),[items,setItems]=useState<Item[]>([]);useEffect(()=>{try{const c=JSON.parse(localStorage.getItem("jk-candle-colors")||"null");if(c?.up)setUpColor(c.up);if(c?.down)setDownColor(c.down);const raw=JSON.parse(localStorage.getItem("jk-indicators")||"[]");const n=normalize(Array.isArray(raw)?raw:[]);setItems(n);if(n.length!==raw.length||n.some((x,i)=>x!==raw[i]))localStorage.setItem("jk-indicators",JSON.stringify(n))}catch{}},[]);
 const emit=(next:Item[])=>{setItems(next);localStorage.setItem("jk-indicators",JSON.stringify(next));window.dispatchEvent(new Event("jk-indicators-changed"))};
 const add=(name:string)=>{const count=items.filter(x=>x.name===name).length;emit([...items,{id:`${name}-${Date.now()}-${count+1}`,name}])};
 const remove=(id:string)=>emit(items.filter(x=>x.id!==id));
 const saveColors=(up:string,down:string)=>{setUpColor(up);setDownColor(down);try{localStorage.setItem("jk-candle-colors",JSON.stringify({up,down}));window.dispatchEvent(new Event("jk-candle-colors-changed"))}catch{}};
 return <div className="max-w-2xl mx-auto px-4 py-8"><h1 className="text-xl font-semibold mb-6">Settings</h1><div className="space-y-6"><section className="border border-[#222] rounded-lg p-4"><div className="flex items-center justify-between mb-2"><h2 className="text-sm font-medium text-[#aaa]">Indicators</h2><span className="text-xs text-[#666]">{items.length} selected</span></div><p className="text-xs text-[#666] mb-4">Tap + to add another instance of the same indicator.</p><div className="space-y-2">{INDICATORS.map(name=>{const count=items.filter(x=>x.name===name).length;return <div key={name} className="flex items-center gap-2 rounded border border-[#333] px-3 py-2"><span className="flex-1 text-sm">{name}{count>0&&<span className="ml-2 text-[10px] text-[#777]">×{count}</span>}</span><button type="button" onClick={()=>add(name)} title={`Add ${name}`} className="w-8 h-8 rounded border border-[#333] flex items-center justify-center text-white hover:border-white"><Plus size={16}/></button>{count>0&&<button type="button" onClick={()=>{const last=[...items].reverse().find(x=>x.name===name);if(last)remove(last.id)}} title={`Remove one ${name}`} className="w-8 h-8 rounded border border-[#333] flex items-center justify-center text-[#aaa] hover:text-white"><Minus size={15}/></button>}</div>})}</div></section><section className="border border-[#222] rounded-lg p-4"><h2 className="text-sm font-medium mb-3 text-[#aaa]">Theme</h2><div className="flex items-center gap-3"><div className="w-10 h-10 bg-black border-2 border-white rounded"/><div><p className="font-medium">Black & White</p><p className="text-xs text-[#666]">Monochrome theme</p></div></div></section><section className="border border-[#222] rounded-lg p-4"><h2 className="text-sm font-medium mb-4 text-[#aaa]">Candle Colors</h2><div className="space-y-4"><div className="flex items-center justify-between"><span className="text-sm">Up candle</span><input type="color" value={upColor} onChange={e=>saveColors(e.target.value,downColor)} className="w-14 h-9 cursor-pointer bg-transparent"/></div><div className="flex items-center justify-between"><span className="text-sm">Down candle</span><input type="color" value={downColor} onChange={e=>saveColors(upColor,e.target.value)} className="w-14 h-9 cursor-pointer bg-transparent"/></div></div></section><section className="border border-[#222] rounded-lg p-4"><h2 className="text-sm font-medium mb-3 text-[#aaa]">Default Timeframe</h2><select className="bg-[#0a0a0a] border border-[#333] rounded px-3 py-2 text-sm w-full max-w-xs"><option>15m</option><option>1H</option><option>4H</option><option>1D</option></select></section><section className="border border-[#222] rounded-lg p-4"><h2 className="text-sm font-medium mb-3 text-[#aaa]">About</h2><p className="text-sm text-[#888]">Jk-Chartings – Clean multi-layout trading charts.<br/>Data from Binance public API (free).</p></section></div></div>}
